apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kitten-game
spec:
  selector:
    matchLabels:
      app: kitten-game
  template:
    metadata:
      labels:
        app: kitten-game
    spec:
      containers:
      - name: kitten-container
        image: bobalink/kitten-game:latest
        command: ["npm", "start"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "70m"
          limits:
            memory: "64Mi"
            cpu: "70m"