# Note: this service doesn't work. Use this command: 
# kubectl expose deployment kitten-game -n dvlp-k8s --type="LoadBalancer"

apiVersion: v1
kind: Service
metadata:
  name: kitten-game
  labels:
    app: kitten-game
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: kitten-game


